name: manage-azure-policy-29d7c063
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Azure policy/policies/Disallow_Sharing_913bd27f-a35c-4fe7-9b2d-93a85aea5751/**'
#      - .github/workflows/manage-azure-policy-29d7c063.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_29d7c063}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Azure policy/policies/Disallow_Sharing_913bd27f-a35c-4fe7-9b2d-93a85aea5751/**
